typography_spectrum: 0.5146278145257384
color:
  brandStrength: 0.6672021895647049
  lightness: 0.5872260862961411
  saturation: 0.7464264426380396
  rhythmicContrast: 0.009294194867834449
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
layout_spectrum: 0.3856536822859198
name: PD's place on the web
navigation:
  - name: PD@ETCETERA
    url: 'http://www.etcetera.nl/en/case_tnt_etc'
    type: external
  - name: BOARDERS
    url: 'https://www.youtube.com/watch?v=t37brlzbmdY'
    type: external
  - name: CHRISTMAS 2015
    url: 'https://www.youtube.com/watch?v=eJGkylqfOrw'
    type: external
  - name: ROAD TO NOWHERE
    url: 'https://www.youtube.com/watch?v=2AVxKBvM_HU'
    type: external
  - name: TOFFE CAMPER
    url: 'https://www.youtube.com/watch?v=h7YaJHFCup8'
    type: external
title: JUST LET IT HAPPEN
description: here we go
