typography_spectrum: 0.32548250001855195
color:
  brandStrength: 0.3685801229439676
  lightness: 0.5157297761179507
  saturation: 0.4708521938882768
  rhythmicContrast: 0.3952735688071698
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
layout_spectrum: 0.5270754948724061
name: PD's place on the web
navigation:
  - name: PD@ETCETERA
    url: 'http://www.etcetera.nl/en/case_tnt_etc'
    type: external
  - name: BOARDERS
    url: 'https://www.youtube.com/watch?v=t37brlzbmdY'
    type: external
title: JUST LET IT HAPPEN
description: here we go
