typography_spectrum: 0.04636887204833329
color:
  brandStrength: 0.005802803207188845
  lightness: 0.5568284161854535
  saturation: 0.5334582708310336
  rhythmicContrast: 0.2073912143241614
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
layout_spectrum: 0.7396623359527439
name: PD's place on the web
navigation:
  - name: PD@ETCETERA
    url: 'http://www.etcetera.nl/en/case_tnt_etc'
    type: external
title: JUST LET IT HAPPEN
description: here we go
